# Generated by Django 4.2.3 on 2023-07-16 18:53

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Services',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=25, verbose_name='Nombre')),
                ('description', models.TextField(verbose_name='Descripcion')),
                ('icon', models.CharField(max_length=150, verbose_name='Clase del icono')),
                ('created', models.DateTimeField(auto_now_add=True, verbose_name='Fecha de creacion')),
                ('updated', models.DateTimeField(auto_now=True, verbose_name='Fecha de actualizacion')),
            ],
            options={
                'verbose_name': 'Lista servicios',
                'verbose_name_plural': '',
                'db_table': '',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='Service',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=25, verbose_name='titulo')),
                ('subtitle', models.CharField(max_length=150, verbose_name='Descripcion')),
                ('is_active', models.BooleanField(default=True, verbose_name='La pagina esta activa?')),
                ('created', models.DateTimeField(auto_now_add=True, verbose_name='Fecha de creacion')),
                ('updated', models.DateTimeField(auto_now=True, verbose_name='Fecha de actualizacion')),
                ('services_list', models.ManyToManyField(to='service.services', verbose_name='Lista de servicios')),
            ],
            options={
                'verbose_name': 'Servicio',
                'db_table': '',
                'managed': True,
            },
        ),
    ]
