# Generated by Django 4.2.3 on 2023-07-16 18:53

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Home',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(default='Hola Soy un', help_text='El valor debe ser maximo de 20 caracteres', max_length=25, verbose_name='Titulo')),
                ('description', models.TextField(blank=True, help_text='El valor debe ser maximo de 150 caracteres', verbose_name='Descripcion')),
                ('is_active', models.BooleanField(default=True, verbose_name='La pagina esta activa?')),
                ('created', models.DateTimeField(auto_now_add=True, verbose_name='Fecha de creacion')),
                ('updated', models.DateTimeField(auto_now=True, verbose_name='Fecha de actualizacion')),
            ],
            options={
                'verbose_name': 'Inicio',
                'db_table': '',
                'managed': True,
            },
        ),
    ]
