# Generated by Django 4.2.3 on 2023-07-22 01:01

import ckeditor.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='home',
            name='description',
            field=ckeditor.fields.RichTextField(blank=True, help_text='El valor debe ser maximo de 150 caracteres', verbose_name='Descripcion'),
        ),
    ]
